### ISSUE TITLE
JavaScript interop

### ISSUE THREAD

**Issue by Zizico2** [emmanuelantony2000/valerie#5]
Is JavaScript interoperability a goal?
I personally don't think it is needed and shouldn't be added if it would add complexity to the framework. 
Anyway I think it would be important to have this (JavaScript interop as a goal, or not, and the reasons why) stated in the readme.

**Comment by emmanuelantony2000** [comment]
Javascript interoperability is definitely possible using the `js_sys` library. And I personally feel, WASM is not built to replace js but work with it to make the ecosystem as a whole better.

**Comment by emmanuelantony2000** [comment]
Closing this issue.
